# Generated by Django 4.2.9 on 2025-02-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_unique_url_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unique_url',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
